# use  mongodb://mongo:mongo@mongo   as connection string in the .env file if running from the docker lambda container
# network needs to be the same for this config and the lambda docker container so that the app can see the db server

# use  mongodb://mongo:mongo@127.0.0.1   as connection string in the .env file if running from host

# mongo data dir is configured in a volume mounted so, data is permanently on the host machine

# mongo express dashboard is available in http://127.0.0.1 from host

# to run this configuration    ./docker_mongo_up.sh
# to stop this configuration   ./docker_mongo_down.sh

version: '3.5'

services:

  mongo:
    image: mongo:3.6.8-stretch
    command:  --auth
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
    - "~/dockermongo/datadir:/data/db"
    networks:
    - mongonetwork

  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
    networks:
    - mongonetwork

networks:
  mongonetwork:
    name: mongonetwork



